
# .github/workflows/sync.yml
name: Sync Fork

#on:
#  schedule:
#  - cron:  "0 * * * *"
  workflow_dispatch:

jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.PAT }}
          upstream_repository: q215613905/TVBoxOS
          target_repository: woshishiq1/TVBoxOS-geren
          upstream_branch: main
          target_branch: master
          force: true
          tags: true
